### ISSUE TITLE
question to deploy

### ISSUE THREAD

**Issue by killmasta93** [drone-plugins/sonarqube-scanner#81]
Hi
trying to deploy, but im getting an error on drone linter: invalid or missing image
this is currently my drone yml

```
kind: pipeline
type: docker
name: default

steps:
  - name: syntax check
    image: docker:latest
    commands:
      - chmod +x ./syntax_check.sh
      - ./syntax_check.sh
  - name: code-analysis
    identifier: run_sonar
    spec:
        image: plugins/sonarqube-scanner:v2.0.2-java17
        reports:
            type: JUnit
            spec:
                paths:
                  - "**/**/*.xml"
        privileged: false
        settings:
            sonar_host: http://192.168.7.106:9001
            sonar_token: sxxxxx
            sources: "."
            binaries: "."
            sonar_name: sonarqube-scanner
            sonar_key: sonarqube-scanner
```
